server:
  port: 8084

spring:
  application:
    name: Api-Gateway


eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka
    fetchRegistry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


zuul:
  routes:
    client-1:
      path: /client-1/**
      serviceId: client-1
      stripPrefix: true

    client-2:
      path: /client-2/**
      serviceId: client-2
      stripPrefix: true

    client-3:
      path: /client-3/**
      serviceId: client-3
      stripPrefix: true

  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 1000000


ribbon:
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000



management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true